# settings.py
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 400
GAME_TITLE = "SOULS"
FPS = 60

PLAYER_GRAVITY = 1
JUMP_HEIGHT = -20

OBSTACLE_MIN_X = 900
OBSTACLE_MAX_X = 1100
OBSTACLE_SPEED = 6

FONT_PATH = 'font/Pixeltype.ttf'
FONT_SIZE = 50
